export const STANDARD_HEADERS: string[] = [
  'Accept',
  'Accept-Charset',
  'Accept-Encoding',
  'Accept-Language',
  'Authorization',
  'Cache-Control',
  'Connection',
  'Content-Disposition',
  'Content-Encoding',
  'Content-Length',
  'Content-Type',
  'Cookie',
  'Date',
  'ETag',
  'Expect',
  'Forwarded',
  'From',
  'Host',
  'If-Match',
  'If-Modified-Since',
  'If-None-Match',
  'If-Range',
  'If-Unmodified-Since',
  'Keep-Alive',
  'Max-Forwards',
  'Origin',
  'Pragma',
  'Proxy-Authorization',
  'Range',
  'Referer',
  'TE',
  'Transfer-Encoding',
  'Upgrade',
  'User-Agent',
  'Via',
  'Warning',
  'X-Forwarded-For',
  'X-Forwarded-Host',
  'X-Forwarded-Proto',
  'X-Request-ID',
  'X-Requested-With',
]

export const HEADER_VALUE_SUGGESTIONS: Record<string, string[]> = {
  'Accept': [
    'application/json',
    'application/xml',
    'text/html',
    'text/plain',
    'text/css',
    'text/javascript',
    'multipart/form-data',
    'application/x-www-form-urlencoded',
    'application/octet-stream',
    'image/png',
    'image/jpeg',
    'image/svg+xml',
    '*/*',
  ],
  'Accept-Charset': [
    'utf-8',
    'iso-8859-1',
    'ascii',
  ],
  'Accept-Encoding': [
    'gzip',
    'deflate',
    'br',
    'gzip, deflate, br',
    'identity',
    '*',
  ],
  'Accept-Language': [
    'en-US',
    'en-GB',
    'id-ID',
    'fr-FR',
    'de-DE',
    'ja-JP',
    'zh-CN',
    '*',
  ],
  'Cache-Control': [
    'no-cache',
    'no-store',
    'max-age=0',
    'max-age=3600',
    'must-revalidate',
    'public',
    'private',
    'no-transform',
  ],
  'Connection': [
    'keep-alive',
    'close',
    'upgrade',
  ],
  'Content-Encoding': [
    'gzip',
    'deflate',
    'br',
    'identity',
  ],
  'Content-Type': [
    'application/json',
    'application/json; charset=utf-8',
    'application/xml',
    'application/x-www-form-urlencoded',
    'multipart/form-data',
    'text/plain',
    'text/plain; charset=utf-8',
    'text/html',
    'text/html; charset=utf-8',
    'text/css',
    'text/javascript',
    'application/javascript',
    'application/octet-stream',
    'application/pdf',
    'image/png',
    'image/jpeg',
    'image/gif',
    'image/svg+xml',
  ],
  'Pragma': [
    'no-cache',
  ],
  'Transfer-Encoding': [
    'chunked',
    'compress',
    'deflate',
    'gzip',
  ],
  'X-Requested-With': [
    'XMLHttpRequest',
  ],
}
